<?xml version="1.0" encoding="UTF-8"?>
<!-- document prolog contains the tags and their types -->
<!DOCTYPE music_library [
  <!ELEMENT music_library (title, artist, country, price, year)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT artist (#PCDATA)>
    <!ELEMENT country (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
    <!ELEMENT year (#PCDATA)>
    <!ENTITY MS "That's Life">
]>
<!-- End of document prolog -->

<!-- Root element OR Document Element-->
<music_library>
  <title>YLO</title>
  <artist>&MS; - jenny Dan</artist>
  <country>Germany</country>
  <price>$ 12</price>
  <year>2002</year>
</music_library>
<!-- End of document -->
